name: Build and Deploy to IPFS Cluster

permissions:
  contents: read
  pull-requests: write
  statuses: write
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy-storacha-and-ipfs-cluster:
    runs-on: ubuntu-latest
    outputs: # This exposes the CID output of the action to the rest of the workflow
      cid: ${{ steps.deploy.outputs.cid }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build hexcamp-welcome
        uses: Tiryoh/actions-mkdocs@v0
        with:
          configfile: "mkdocs-hexcamp-welcome.yml"

      - name: Build vichex-welcome
        uses: Tiryoh/actions-mkdocs@v0
        with:
          configfile: "mkdocs-vichex-welcome.yml"

      - name: Build vichex-arts-map
        uses: Tiryoh/actions-mkdocs@v0
        with:
          configfile: "mkdocs-vichex-arts-map.yml"

      - name: List dirs
        run: ls -l site/*

      - name: Remove timestamps
        run: sudo perl -pi -e 's/^Build Date UTC.*//' site/*/index.html

      - name: Remove compressed sitemap.xml.gz files
        run: sudo rm -f site/*/sitemap.xml.gz

      - uses: ipfs/ipfs-deploy-action@v1
        name: Deploy to Storacha and IPFS
        id: deploy
        with:
          path-to-deploy: site
          storacha-key: ${{ secrets.STORACHA_KEY }}
          storacha-proof: ${{ secrets.STORACHA_PROOF }}
          cluster-url: ${{ secrets.CLUSTER_URL }}
          cluster-user: ${{ secrets.CLUSTER_USER }}
          cluster-password: ${{ secrets.CLUSTER_PASSWORD }}
          github-token: ${{ github.token }}

      - name: Check dns trace
        run: dig +trace 6kgv3nw3nw2q.seahex.org

      - name: Check dns trace after CNAME
        run: dig +trace 5.6.6.6.6.6.6.6.6.6.6.6.5.2.3.20.h3.seahex.org.

      - name: Check dns
        run: dig 6kgv3nw3nw2q.seahex.org

      - name: Test ping
        run: ping -c 1 6kgv3nw3nw2q.seahex.org || true

      - name: Call hackmd-updater API with CID
        run: curl -X POST https://6kgv3nw3nw2q.seahex.org/publish/${{ steps.deploy.outputs.cid }}
